if $programname == 'kvm_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/kvm_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}