[Application]
FileLogger\Age=3
FileLogger\AgeType=0
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/var/ugreen/log/download_serv_qbittorrent
MemoryWorkingSetLimit=512

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=true
Session\AlternativeGlobalDLSpeedLimit=0
Session\AlternativeGlobalUPSpeedLimit=0
Session\AlternativeRateLimitsEnabled=false
Session\BandwidthSchedulerEnabled=false
Session\DHTEnabled=true
Session\DefaultSavePath=/volume1/@appstore/com.ugreen.downloadmgr/Downloads
Session\DisableAutoTMMByDefault=false
Session\ExcludedFileNames=
Session\GlobalDLSpeedLimit=0
Session\GlobalMaxInactiveSeedingMinutes=-1
Session\GlobalMaxRatio=2.000000
Session\GlobalMaxSeedingMinutes=-1
Session\GlobalUPSpeedLimit=50
Session\uTPRateLimited=true
Session\IncludeOverheadInLimits=false
Session\IgnoreLimitsOnLAN=false
Session\MaxActiveCheckingTorrents=20
Session\MaxActiveDownloads=99999
Session\MaxActiveTorrents=99999
Session\MaxActiveUploads=99999
Session\MaxConnections=50
Session\MaxConnectionsPerTorrent=50
Session\MaxUploads=20
Session\MaxUploadsPerTorrent=4
Session\Port=51413
Session\QueueingSystemEnabled=false
Session\SSL\Port=27457
Session\ShareLimitAction=Stop
Session\TempPath=/volume1/@appstore/com.ugreen.downloadmgr/Downloads
Session\TempPathEnabled=false
Session\UseAlternativeGlobalSpeedLimit=false
Session\PeXEnabled=true
Session\LSDEnabled=true
TrackerEnabled=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Advanced\trackerPort=16666
Advanced\trackerPortForwarding=false
Connection\Port=18080
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/volume1/@appstore/com.ugreen.downloadmgr/Downloads
Downloads\TempPath=/volume1/@appstore/com.ugreen.downloadmgr/Downloads
General\Locale=zh_CN
MailNotification\req_auth=true
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(U2CZjOyvwYw1ucsEq4N2nQ==:tR14QhYQIKL0XBWBaOny657f9Rmd+2MANUjsPC91a93D6sI3pbPt+A2nhwh9SR/TxrX9A5/RKBm7+guPiKny3Q==)"
WebUI\Port=18080
WebUI\Address=127.0.0.1
WebUI\ServerDomains=*
WebUI\Username=ugreen
WebUI\CSRFProtection=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
