location ~ ^/ugreen/v1/comic {
    proxy_set_header Host $host;
    proxy_set_header Port $server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://comic_backend;
    proxy_intercept_errors on;
    fastcgi_read_timeout 3600;
    proxy_read_timeout 3600;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
}
