location ~ ^/ugreen/v1/office/ {
        client_max_body_size 0;
        proxy_request_buffering off;

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        proxy_set_header Host $http_host;
        proxy_set_header Port $server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_intercept_errors on;
        proxy_pass http://unix:/var/ugreen/office_serv.sock;
}

location /ugoffice/ {
        set $office_scheme $scheme;
        if ($http_host ~* "\.ug\.link$") {
            set $office_scheme 'https';
        }
        if ($http_x_forwarded_ugreen_proto ~* "^https?$") {
            set $office_scheme $http_x_forwarded_ugreen_proto;
        }

        set $office_host $http_host;
        if ($http_x_forwarded_ugreen_for != "") {
            set $office_host $http_x_forwarded_ugreen_for;
        }

        proxy_set_header Host $office_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Host $office_host;
        proxy_set_header X-Forwarded-Proto $office_scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_pass http://unix:/tmp/ugoffice.sock:/;
}

location /cache/files/data/ {
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_pass http://unix:/tmp/ugoffice.sock;
}

location /printfile/ {
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_pass http://unix:/tmp/ugoffice.sock;
}
