if $programname == 'cameramgr_serv' then {
    action(type="omfile"
        file="/var/ugreen/log/cameramgr_serv.slog"
        template="UgLogFormat"
        fileCreateMode="0600"
        dirCreateMode="0755"
        createDirs="on")
    stop
}
if $programname == 'cameramgr_serv_gin' then {
    action(type="omfile"
        file="/var/ugreen/log/cameramgr_serv_gin.slog"
        template="UgLogFormat"
        fileCreateMode="0600"
        dirCreateMode="0755"
        createDirs="on")
    stop
}
if $programname == 'camerams_serv' then {
    action(type="omfile"
        file="/var/ugreen/log/stream_serv.slog"
        template="UgLogFormat"
        fileCreateMode="0600"
        dirCreateMode="0755"
        createDirs="on")
    stop
}