location ~ ^/ugreen/v1/versionExplorer/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-URI $request_uri;

        proxy_pass http://version_backend;  #这里指向stream的upstream配置，需要全局唯一
        # 必须为 1.1 且不发送 Connection: close，才能复用上游连接，默认1.0
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_intercept_errors on;
}

location ~ ^/ugreen/v2/versionExplorer/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-URI $request_uri;

        proxy_pass http://version_backend;  #这里指向stream的upstream配置，需要全局唯一
        # 必须为 1.1 且不发送 Connection: close，才能复用上游连接，默认1.0
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_intercept_errors on;
}
