if $programname == 'photo_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/photo_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'ai_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/ai_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'card_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/card_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'common_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/common_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'itm_image_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/itm_image_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'nlp_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/nlp_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'ocr_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/ocr_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'off_line_learning_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/off_line_learning_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'pet_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/pet_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'save_head_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/save_head_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'scene_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/scene_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'similar_cluster_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/similar_cluster_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'vs_db_cluster_ai_sdk_tool' then {
    action(type="omfile"
           file="/var/ugreen/log/vs_db_cluster_ai_sdk_tool.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}