if $programname == 'snapshot_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/snapshot_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}

if $programname == 'snapshot_serv_gin' then {
    action(type="omfile"
           file="/var/ugreen/log/snapshot_serv_gin.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}

if $programname == 'snapshot_tool_exist_snapshot' then {
    action(type="omfile"
           file="/var/ugreen/log/snapshot_tool_exist_snapshot.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}


if $programname == 'snapshot_tool_migrate_home' then {
    action(type="omfile"
           file="/var/ugreen/log/snapshot_tool_migrate_home.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}

if $programname == 'snapshot_tool_migrate_users' then {
    action(type="omfile"
           file="/var/ugreen/log/snapshot_tool_migrate_users.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}