if $programname == 'note_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/note_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'note_serv_gin' then {
    action(type="omfile"
           file="/var/ugreen/log/note_serv_gin.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
