if $programname == 'editor_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/editor_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}