if $programname == 'download_serv' then {
    action(type="omfile"
           file="/var/ugreen/log/download_serv.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'download_serv_gin' then {
    action(type="omfile"
           file="/var/ugreen/log/download_serv_gin.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'download_serv_aria2' then {
    action(type="omfile"
           file="/var/ugreen/log/download_serv_aria2.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'download_serv_qbittorrent' then {
    action(type="omfile"
           file="/var/ugreen/log/download_serv_qbittorrent.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
if $programname == 'download_serv_trace' then {
    action(type="omfile"
           file="/var/ugreen/log/download_serv_trace.slog"
           template="UgLogFormat"
           fileCreateMode="0600"
           dirCreateMode="0755"
           createDirs="on")
    stop
}
