location ~ ^/ugreen/v1/vault/ {
        client_body_timeout 10s;
        client_max_body_size 0;
        client_body_buffer_size 15m;

        proxy_pass_request_headers on;
        proxy_request_buffering off;
        fastcgi_request_buffering  off;
        scgi_request_buffering off;
        proxy_buffering off;
        fastcgi_buffering off;
        scgi_buffering off;
        resolver_timeout 5s;
        keepalive_timeout 60s;
        tcp_nopush on;
        tcp_nodelay on;
        proxy_redirect off;
        chunked_transfer_encoding on;
        proxy_cache off;
        proxy_connect_timeout 300s;
        proxy_send_timeout 12h;
        proxy_read_timeout 12h;
        proxy_max_temp_file_size 0;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-URI $request_uri;

        proxy_pass http://unix:/var/ugreen/vault_serv.sock;
        proxy_intercept_errors on;
}
